[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"

[dev]
 framework = '#custom'
 command = "npm run dev"
 targetPort = 5000
 port = 5001
 publish = "public"
 jwtRolePath = 'app_metadata.authorization.roles'
 autoLaunch = true

[functions]
 directory = "functions/"